# Qualitative report

In this section, you will find information and guidance about your qualitative report and a report writing guide. Please make sure to familiarise yourself with the AIS and FIS on Moodle before starting to work on the report.

## What is the qualitative report?

You will be asked to write an individual qualitative report on one of three secondary data topics. You should conduct Thematic Analysis on your chosen dataset.Watch this video (ADD LINK) for an overview about the report, and make sure you have accessed the AIS and FIS on Moodle before you start working on the report. 

## Report datasets and how to use UK data service

Before accessing your datasets, watch [THIS VIDEO](https://uofglasgow.zoom.us/rec/play/vsROyrWqPj8G3f21Tff5nCJ4iXOUSGCu7BT7N4xg7zMWIU9tCJPsTT4pEcJfD46tjf01xtdffznX__oq.3cjWmKRYD1qOsQzX?canPlayFromShare=true&from=share_recording_detail&startTime=1676397171000&componentName=rec-play&originRequestUrl=https%3A%2F%2Fuofglasgow.zoom.us%2Frec%2Fshare%2FFtJDqqO9WKzzIZz6exHF2K4FJQJMcHQyrxF-btchS3lUd0q-UY6mYDq1u3zttqzQ.sQK03tO0hhi67guf%3FstartTime%3D1676397171000) on how to use UK data service and for a bit of information about the datasets. Please note that two of the datasets are on sensitive topics, and contain information that may be upsetting; make sure to familiarise yourself with the interview schedules and have a quick scan of the data before you decide which dataset to work with. 

You can access the UK data service [HERE](https://beta.ukdataservice.ac.uk/myaccount/login)

You can choose one of the three available datasets: 
  1. [Interviews with disabled young people and carers](https://beta.ukdataservice.ac.uk/datacatalogue/studies/study?id=854556)
  2. [LGBT+ networks in the workplace](https://beta.ukdataservice.ac.uk/datacatalogue/studies/study?id=855322)
  3. [Incentives of sharing research data](https://beta.ukdataservice.ac.uk/datacatalogue/studies/study?id=851540)

## Developing a research question

As part of writing up your qualitative report, we ask that you develop a research question to help you guide your enquiry. Here is some guidance on how to get started:

### Getting started with the data

For this report, you are using secondary data. This means that the data have already been collected using specific interview questions  - before you start thinking about your research question, make sure to have a look at the interview schedule for your chosen dataset (this document will list the interview questions the researchers asked the participants). This should guide you in what questions you might ask and what kind of question you might be able to answer with the available data. You can also take a look at some of the transcripts to get a better feel for the data.

Looking at the data before you decide on your RQ might feel a bit strange after RM1, but remember that you are not doing hypothesis-testing with qualitative designs  - it is quite normal for a qualitative research question to change during the research process, and this is completely fine as you are not statistically testing for a specific effect.

Be mindful that you are not making a research question that is actually one of the interview questions - your RQ should be broader than what the specific interview questions are.

One of the most common mistakes that students make when framing their research question in RM2 is that it is a little too 'quant' in nature. This makes perfect sense, as most of your research methods education so far in the programme has been focused on quant! However, for your qual report, your RQ should be a little different to the RQs you are used to. 

Look at the following examples:

1. How does poor sleep impact on wellbeing? 
2. What is the difference in wellbeing between those who belong to university and those who don't?

Both questions are a bit too quantitative in nature (i.e. 1 is causal and 2 is about a difference between groups). They would also benefit from thinking about what is being looked at, specifically (e.g. views, opinions, experiences).

We'd perhaps rephrase these as follows:

1.  What are students' perceptions of the relationship between sleep and wellbeing?
2. What are online conversion students' experiences of belonging to University? How do these experiences relate to perceived wellbeing?

These questions are now a bit more in line with qualitative and are specific about what they are asking in each (and also what the group of interest is). The second one covers a bit more than the first, which is why it is split into two (a main RQ and a subsidiary one)

### Some tips for developing a research question

  * **Communication:** Keep your research question simple and specific. If you have a very broad question, it can be helpful to break the question down into smaller sub-questions.
  * **Type of question:**  We want the RQ to tap in to more than ‘descriptive’ experience but also offer scope to explore the ‘how’ and ‘why’ of psychological experience–Is the question asking about experiences, understanding, accounts of practice, or influencing factors?  
  * **Practical constraints:** Can the question realistically be explored using thematic analysis and using secondary data? Try not to cover too much
  * **Guiding:** Remember that your RQ guides your enquiry but shouldn't be restrictive  - it's not the case that you are unable to report themes that don't directly answer your RQ. 
  * **Flexibility:** Research questions are more flexible than hypotheses-it is acceptable for the focus of the RQ to be refined during/after data collection.
  
## Activities to help with writing

### Evaluation in introductions

### Evaluation in discussions

### Thematic analysis evaluation activity

## Qualitative report guide